filebrowser_safe/urls.py
from django.conf.urls import *

urlpatterns = patterns('',

    # filebrowser urls
    url(r'^browse/$', 'filebrowser_safe.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser_safe.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser_safe.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser_safe.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser_safe.views.delete', name="fb_delete"),
    url(r'^check_file/$', 'filebrowser_safe.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser_safe.views._upload_file', name="fb_do_upload"),

)

filebrowser_safe/forms.py
# coding: utf-8

# imports
import os
import re

# django imports
from django import forms
from django.utils.translation import ugettext as _

# filebrowser imports
from filebrowser_safe.settings import FOLDER_REGEX


alnum_name_re = re.compile(FOLDER_REGEX)


class MakeDirForm(forms.Form):
    """
    Form for creating Folder.
    """

    def __init__(self, path, *args, **kwargs):
        self.path = path
        super(MakeDirForm, self).__init__(*args, **kwargs)

    dir_name = forms.CharField(
        widget=forms.TextInput(attrs=dict({'class': 'vTextField'},
        max_length=50, min_length=3)),
        label=_(u'Name'),
        help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'),
        required=True)

    def clean_dir_name(self):
        if self.cleaned_data['dir_name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['dir_name']):
                raise forms.ValidationError(
                    _(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if os.path.isdir(os.path.join(self.path, self.cleaned_data['dir_name'])):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return self.cleaned_data['dir_name']


class RenameForm(forms.Form):
    """
    Form for renaming Folder/File.
    """

    def __init__(self, path, file_extension, *args, **kwargs):
        self.path = path
        self.file_extension = file_extension
        super(RenameForm, self).__init__(*args, **kwargs)

    name = forms.CharField(
        widget=forms.TextInput(attrs=dict({'class': 'vTextField'},
        max_length=50, min_length=3)),
        label=_(u'New Name'),
        help_text=_('Only letters, numbers, underscores, spaces and hyphens are allowed.'),
        required=True)

    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if os.path.isdir(os.path.join(self.path, self.cleaned_data['name'])):
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif os.path.isfile(os.path.join(self.path, self.cleaned_data['name'] + self.file_extension)):
                raise forms.ValidationError(_(u'The File already exists.'))
        return self.cleaned_data['name']

filebrowser_safe/templates/filebrowser/append.html
{% load i18n future %}

<div class="module">
    <table>
        <caption>{% trans "FileBrowser" %}</caption>
        <tr class="row2">
            <th scope="row"><a href="{% url "fb_browse" %}">{% trans "FileBrowser" %}</a></th>
            <td> </td>
            <td> </td>
        </tr>
    </table>
</div>

filebrowser_safe/templates/filebrowser/custom_field.html
{% load mezzanine_tags i18n future %}
<style>
.mezz-fb-thumbnail {display:inline; margin-left:5px !important;}
.mezz-fb-thumbnail img {width:100px; height:100px; margin-top:0 !important;}
.vFileBrowseField {display:none;}
</style>
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value }}" />
<a style="padding:5px 16px;" href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{% url "fb_browse" %}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="fb_show">
    <img src="{{ final_attrs.search_icon }}" alt="" />
</a>
{% ifequal value.filetype "Image" %}
<p class="help mezz-fb-thumbnail" id="help_{{ final_attrs.id }}">
    <a href="{{ MEDIA_URL }}{{ value.path }}" target="_blank" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" src="{{ MEDIA_URL }}{% thumbnail value.path 100 100 %}" class="preview" />
    </a>
</p>
{% else %}
<p class="help" id="help_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endifequal %}
{% if not self.is_required %}
    <p class="help mezz-fb-clear" id="clear_{{ final_attrs.id }}" style="display:{% if value %}inline{% else %}none{% endif %}; margin:0 10px;">
        <a href="javascript:FileBrowser.clear('{{ final_attrs.id }}');">{% trans "Clear" %}</a>
    </p>
{% endif %}
{% if final_attrs.DEBUG %}
<p>
    <strong>Path</strong> {{ value.path }}<br />
    <strong>FileType</strong> {{ value.filetype }}<br /><br />
    <strong>Directory</strong> {{ final_attrs.directory }}<br />
    <strong>Extensions</strong> {{ final_attrs.extensions }}<br />
    <strong>Format</strong> {{ final_attrs.format }}
</p>
{% endif %}

filebrowser_safe/templates/filebrowser/index.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n future static fb_tags fb_pagination %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/changelist.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
{{ block.super }}

{% ifequal query.pop '1' %} <!-- FileBrowseField -->
<script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_FileBrowseField.js"></script>
{% endifequal %}

{% ifequal query.pop '2' %} <!-- TinyMCE -->
<script language="javascript" type="text/javascript" src="{{ settings_var.URL_TINYMCE }}tiny_mce_popup.js"></script>
<script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_TinyMCE.js"></script>
{% if query.mce_rdomain %}<script language="javascript">document.domain = "{{ query.mce_rdomain }}"</script>{% endif %}
{% endifequal %}

{% ifequal query.pop '3' %} <!-- CKeditor (former "FCKeditor") -->
<script language="javascript" type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/FB_CKEditor.js"></script>
{% endifequal %}

{{ media }}

<script type="text/javascript" src="{% static "grappelli/js/admin/Changelist.js" %}"></script>

{% if not actions_on_top and not actions_on_bottom %}
<style>
    #changelist table thead th:first-child { width: inherit; }
</style>
{% endif %}
{% endblock %}

{% block rtl_styles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/rtl.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

{% block content_title %}<h1>{% include "filebrowser/include/breadcrumbs.html" %}</h1>{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    {% block object-tools %}
    <ul class="object-tools">
        <li><a href="{% url "fb_mkdir" %}{% query_string '' 'p' %}">{% trans "New Folder" %}</a></li>
        <li><a href="{% url "fb_upload" %}{% query_string '' 'p' %}" class="focus">{% trans "Upload" %}</a></li>
    </ul>
    {% endblock %}
    <div class="module filtered" id="changelist">
        <div class="changelist-content">
            <div class="result-list-container">
                {% if results_var.results_current %}
                <div class="result-list">
                    <table cellspacing="0">
                        {% include "filebrowser/include/tableheader.html" %}
                        <tbody>
                        {% include "filebrowser/include/filelisting.html" %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
                {% pagination %}
            </div>
        </div>
        <div id="changelist-filter">
            {% include "filebrowser/include/toolbar.html" %}
            <div class="module filter">
                {% include "filebrowser/include/filter.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

filebrowser_safe/templates/filebrowser/makedir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n static fb_tags %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

{% block content_title %}<h1>{% include "filebrowser/include/breadcrumbs.html" %}</h1>{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form action="{% query_string '' 'p' %}" method="post">{% csrf_token %}
    <div>
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
        <div class="form-row {% if form.dir_name.errors %}errors{% endif %}">
            {% if form.dir_name.errors %}<ul class="errorlist">{{ form.dir_name.errors }}</ul>{% endif %}
            <label class="required" for="id_dir_name">{{ form.dir_name.label }}</label>
            {{ form.dir_name }}
            <p class="help">
                {{ form.dir_name.help_text|safe }}
                {% if settings_var.CONVERT_FILENAME %}<br />{% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}{% endif %}
            </p>
        </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% trans 'Submit' %}" class="default" /><br class="clear" />
        </div>
    </div>
    </form>
</div>
{% endblock %}

filebrowser_safe/templates/filebrowser/rename.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n static fb_tags %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

{% block content_title %}<h1>{% include "filebrowser/include/breadcrumbs.html" %}</h1>{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">
    {% csrf_token %}
    <div>
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
        <div class="form-row {% if form.dir_name.errors %}errors{% endif %}">
            {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
            <label class="required" for="id_dir_name">{{ form.name.label }}</label>
            {{ form.name }}
            {% if file_extension %}<b>{{ file_extension }}</b>{% endif %}
            {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
        </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% trans 'Submit' %}" class="default" />
        </div>
    </div>
    </form>
</div>
{% endblock %}

filebrowser_safe/templates/filebrowser/upload.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n l10n future static fb_tags mezzanine_tags %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript" src="../../jsi18n/"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery.uploadify.v2.1.4.min.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/swfobject.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        {% url "static_proxy" as static_proxy_url %}
        var proxy = '{{ static_proxy_url }}';
        if (proxy) {
            proxy += '?u=';
        }
        $('#id_file').uploadify({
            'uploader'          : proxy + '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.swf',
            'script'            : '{% url "fb_do_upload" %}',
            'scriptData'        : {'session_key': '{{session_key}}'},
            'checkScript'       : '{% url "fb_check" %}',
            'cancelImg'         : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/cancel.png',
            'auto'              : false,
            'folder'            : '{{ query.dir|escapejs }}',
            'multi'             : true,
            'fileDesc'          : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
            'fileExt'           : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
            'sizeLimit'         : {{ settings_var.MAX_UPLOAD_SIZE|unlocalize }},
            'scriptAccess'      : 'always',
            'queueSizeLimit'    : 50,
            'simUploadLimit'    : 1,
            'width'             : 300,
            'height'            : 30,
            'hideButton'        : false,
            'wmode'             : 'transparent',
            'removeCompleted'   : false,
            'onAllComplete' : function(event,data) {location = '{% url "fb_browse" %}{% query_string '' 'p' %}'},
            translations        : {
                                  browseButton: '{% trans "BROWSE" %}',
                                  error: '{% trans "An Error occured" %}',
                                  completed: '{% trans "Completed" %}',
                                  replaceFile: '{% trans "Do you want to replace the file" %}',
                                  unitKb: '{% trans "KB" %}',
                                  unitMb: '{% trans "MB" %}'
            }
        });
        $('input:submit').click(function(){
            $('#id_file').uploadifyUpload();
            return false;
        });
        $('a.deletelink').click(function(evt){
                $('#id_file').uploadifyClearQueue();
                return false;
        });
    });
    </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block coltype %}colM{% endblock %}
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

{% block content_title %}<h1>{% include "filebrowser/include/breadcrumbs.html" %}</h1>{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"></div>{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form>
    <div>
        <fieldset class="module aligned">
        <div class="form-row">
            <input type="File" id="id_file" />
        </div>
        </fieldset>

        <fieldset class="module aligned collapse-closed">
        <h2>{% trans "Help" %}</h2>
        <div class="form-row" >
            {% for extension in settings_var.EXTENSIONS.items %}
            {% ifnotequal extension.0 'Folder' %}
            <label class="required">{% if forloop.first %}{% trans "Allowed" %}:{% else %}&nbsp;{% endif %}</label>
            <p>{{ extension.0|safe }} ({{ extension.1|join:", "|safe }})</p>
            {% endifnotequal %}
            {% endfor %}
        </div>
        <div class="form-row" >
            <label class="required">{% trans "Max. Filesize" %}:</label>
            <p>{{ settings_var.MAX_UPLOAD_SIZE|filesizeformat }}</p>
        </div>
        {% if settings_var.CONVERT_FILENAME %}
        <div class="form-row" >
            <label class="required">&nbsp;</label>
            <p>
                {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
            </p>
        </div>
        {% endif %}
        </fieldset>

        <div class="submit-row">
            <p class="deletelink-box">
                <a class="deletelink" href="javascript://">{% trans "Clear Queue" %}</a>
            </p>
            <input class="default" type="submit" name="_save" value='{% trans "Upload" %}' />
        </div>

    </div>
    </form>
</div>
{% endblock %}